# Generated by Django 3.0.8 on 2020-09-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_email', models.CharField(max_length=20)),
                ('contact_phone', models.CharField(max_length=50)),
                ('contact_subject', models.CharField(max_length=100)),
                ('contact_message', models.CharField(max_length=500)),
            ],
        ),
    ]
