# Generated by Django 3.0.8 on 2020-09-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_course', models.CharField(choices=[('ADCA(Advance Diploma in Computer Application)', 'ADCA(Advance Diploma in Computer Application)'), ('CCA(Certificate in Computer Application)', 'CCA(Certificate in Computer Application)'), ('CCC(Course on Computer Concepts)', 'CCC(Course on Computer Concepts)'), ('DTP(Desktop Publication)', 'DTP(Desktop Publication)'), ('(Tally ERP 9)computer Accounting Course', '(Tally ERP 9)computer Accounting Course'), ('IGD Bombay Art', 'IGD Bombay Art'), ('Computerized Mobile Repairing', 'Computerized Mobile Repairing'), ('AutoCad', 'AutoCad'), ('Computer Hardware & Networking', 'Computer Hardware & Networking'), ('MCA(Master of Computer Application)', 'MCA(Master of Computer Application)'), ('PGDCA', 'PGDCA'), ('BCA(Bachlors of Computer Application)', 'BCA(Bachlors of Computer Application)'), ('Web Designing', 'Web Designing'), ('DCA 1 Year(Diploma in Computer Application)', 'DCA 1 Year(Diploma in Computer Application)'), ('DRA(Diploma in Refrigeration & Air Conditioning)', 'DRA(Diploma in Refrigeration & Air Conditioning)')], max_length=100)),
                ('c_branch', models.CharField(choices=[('br', 'br'), ('acc', 'acc'), ('gr', 'gr'), ('fips', 'fips'), ('sknb', 'sknb')], max_length=50)),
                ('c_roll', models.CharField(max_length=5)),
            ],
        ),
    ]
